/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as DashboardImport } from './routes/dashboard'
import { Route as IndexImport } from './routes/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as DashboardSettingsImport } from './routes/dashboard/settings'
import { Route as DashboardRequestsImport } from './routes/dashboard/requests'
import { Route as DashboardPurchasesImport } from './routes/dashboard/purchases'
import { Route as DashboardHelpImport } from './routes/dashboard/help'
import { Route as DashboardFavoritesImport } from './routes/dashboard/favorites'
import { Route as DashboardDisclaimerImport } from './routes/dashboard/disclaimer'
import { Route as DashboardAboutImport } from './routes/dashboard/about'

// Create Virtual Routes

const DashboardPeersLazyImport = createFileRoute('/dashboard/peers')()
const DashboardAvailabilitiesLazyImport = createFileRoute(
  '/dashboard/availabilities',
)()

// Create/Update Routes

const DashboardRoute = DashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardPeersLazyRoute = DashboardPeersLazyImport.update({
  id: '/peers',
  path: '/peers',
  getParentRoute: () => DashboardRoute,
} as any).lazy(() =>
  import('./routes/dashboard/peers.lazy').then((d) => d.Route),
)

const DashboardAvailabilitiesLazyRoute =
  DashboardAvailabilitiesLazyImport.update({
    id: '/availabilities',
    path: '/availabilities',
    getParentRoute: () => DashboardRoute,
  } as any).lazy(() =>
    import('./routes/dashboard/availabilities.lazy').then((d) => d.Route),
  )

const DashboardSettingsRoute = DashboardSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardRequestsRoute = DashboardRequestsImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardPurchasesRoute = DashboardPurchasesImport.update({
  id: '/purchases',
  path: '/purchases',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardHelpRoute = DashboardHelpImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardFavoritesRoute = DashboardFavoritesImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardDisclaimerRoute = DashboardDisclaimerImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => DashboardRoute,
} as any)

const DashboardAboutRoute = DashboardAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => DashboardRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/about': {
      id: '/dashboard/about'
      path: '/about'
      fullPath: '/dashboard/about'
      preLoaderRoute: typeof DashboardAboutImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/disclaimer': {
      id: '/dashboard/disclaimer'
      path: '/disclaimer'
      fullPath: '/dashboard/disclaimer'
      preLoaderRoute: typeof DashboardDisclaimerImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/favorites': {
      id: '/dashboard/favorites'
      path: '/favorites'
      fullPath: '/dashboard/favorites'
      preLoaderRoute: typeof DashboardFavoritesImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/help': {
      id: '/dashboard/help'
      path: '/help'
      fullPath: '/dashboard/help'
      preLoaderRoute: typeof DashboardHelpImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/purchases': {
      id: '/dashboard/purchases'
      path: '/purchases'
      fullPath: '/dashboard/purchases'
      preLoaderRoute: typeof DashboardPurchasesImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/requests': {
      id: '/dashboard/requests'
      path: '/requests'
      fullPath: '/dashboard/requests'
      preLoaderRoute: typeof DashboardRequestsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/availabilities': {
      id: '/dashboard/availabilities'
      path: '/availabilities'
      fullPath: '/dashboard/availabilities'
      preLoaderRoute: typeof DashboardAvailabilitiesLazyImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/peers': {
      id: '/dashboard/peers'
      path: '/peers'
      fullPath: '/dashboard/peers'
      preLoaderRoute: typeof DashboardPeersLazyImport
      parentRoute: typeof DashboardImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof DashboardImport
    }
  }
}

// Create and export the route tree

interface DashboardRouteChildren {
  DashboardAboutRoute: typeof DashboardAboutRoute
  DashboardDisclaimerRoute: typeof DashboardDisclaimerRoute
  DashboardFavoritesRoute: typeof DashboardFavoritesRoute
  DashboardHelpRoute: typeof DashboardHelpRoute
  DashboardPurchasesRoute: typeof DashboardPurchasesRoute
  DashboardRequestsRoute: typeof DashboardRequestsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardAvailabilitiesLazyRoute: typeof DashboardAvailabilitiesLazyRoute
  DashboardPeersLazyRoute: typeof DashboardPeersLazyRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAboutRoute: DashboardAboutRoute,
  DashboardDisclaimerRoute: DashboardDisclaimerRoute,
  DashboardFavoritesRoute: DashboardFavoritesRoute,
  DashboardHelpRoute: DashboardHelpRoute,
  DashboardPurchasesRoute: DashboardPurchasesRoute,
  DashboardRequestsRoute: DashboardRequestsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardAvailabilitiesLazyRoute: DashboardAvailabilitiesLazyRoute,
  DashboardPeersLazyRoute: DashboardPeersLazyRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/disclaimer': typeof DashboardDisclaimerRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/purchases': typeof DashboardPurchasesRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/availabilities': typeof DashboardAvailabilitiesLazyRoute
  '/dashboard/peers': typeof DashboardPeersLazyRoute
  '/dashboard/': typeof DashboardIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/disclaimer': typeof DashboardDisclaimerRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/purchases': typeof DashboardPurchasesRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/availabilities': typeof DashboardAvailabilitiesLazyRoute
  '/dashboard/peers': typeof DashboardPeersLazyRoute
  '/dashboard': typeof DashboardIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/about': typeof DashboardAboutRoute
  '/dashboard/disclaimer': typeof DashboardDisclaimerRoute
  '/dashboard/favorites': typeof DashboardFavoritesRoute
  '/dashboard/help': typeof DashboardHelpRoute
  '/dashboard/purchases': typeof DashboardPurchasesRoute
  '/dashboard/requests': typeof DashboardRequestsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/availabilities': typeof DashboardAvailabilitiesLazyRoute
  '/dashboard/peers': typeof DashboardPeersLazyRoute
  '/dashboard/': typeof DashboardIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/about'
    | '/dashboard/disclaimer'
    | '/dashboard/favorites'
    | '/dashboard/help'
    | '/dashboard/purchases'
    | '/dashboard/requests'
    | '/dashboard/settings'
    | '/dashboard/availabilities'
    | '/dashboard/peers'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/about'
    | '/dashboard/disclaimer'
    | '/dashboard/favorites'
    | '/dashboard/help'
    | '/dashboard/purchases'
    | '/dashboard/requests'
    | '/dashboard/settings'
    | '/dashboard/availabilities'
    | '/dashboard/peers'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/about'
    | '/dashboard/disclaimer'
    | '/dashboard/favorites'
    | '/dashboard/help'
    | '/dashboard/purchases'
    | '/dashboard/requests'
    | '/dashboard/settings'
    | '/dashboard/availabilities'
    | '/dashboard/peers'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/dashboard"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/dashboard": {
      "filePath": "dashboard.tsx",
      "children": [
        "/dashboard/about",
        "/dashboard/disclaimer",
        "/dashboard/favorites",
        "/dashboard/help",
        "/dashboard/purchases",
        "/dashboard/requests",
        "/dashboard/settings",
        "/dashboard/availabilities",
        "/dashboard/peers",
        "/dashboard/"
      ]
    },
    "/dashboard/about": {
      "filePath": "dashboard/about.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/disclaimer": {
      "filePath": "dashboard/disclaimer.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/favorites": {
      "filePath": "dashboard/favorites.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/help": {
      "filePath": "dashboard/help.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/purchases": {
      "filePath": "dashboard/purchases.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/requests": {
      "filePath": "dashboard/requests.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/settings": {
      "filePath": "dashboard/settings.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/availabilities": {
      "filePath": "dashboard/availabilities.lazy.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/peers": {
      "filePath": "dashboard/peers.lazy.tsx",
      "parent": "/dashboard"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx",
      "parent": "/dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
