name: Docker

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
    paths-ignore:
      - '**/*.md'
      - '.gitignore'
      - 'docker/**'
      - '!docker/Dockerfile'
      - '.github/**'
      - '!.github/workflows/docker.yml'
      - 'LICENSE-*'
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and Push
    uses: durability-labs/github-actions/.github/workflows/docker-reusable.yml@main
    with:
      docker_file: docker/Dockerfile
      dockerhub_repo: durabilitylabs/archivist-app
      build_args: |
        VITE_ARCHIVIST_API_URL=${VITE_ARCHIVIST_API_URL}
        VITE_GEO_IP_URL=${VITE_GEO_IP_URL}
      tag_latest: ${{ github.ref_name == github.event.repository.default_branch || startsWith(github.ref, 'refs/tags/') }}
    secrets: inherit
